server:
  servlet:
    context-path: /content
  port: 63040
spring:
  application:
    name: content-api
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        group: study-plus-project
        namespace: dev
  freemarker:
    cache: false
    enabled: true
    settings:
      template_update_delay: 0
    suffix: .ftl
    charset: utf-8
    template-loader-path: classpath:/templates/

logging:
  config: classpath:log4j2-dev.xml
swagger:
  title: "华中科技大学内容管理系统"
  description: "内容系统管理系统对课程相关信息进行业务管理数据"
  base-package: com.kevintam.content
  enabled: true
  version: 1.0.0
